[ART]
   [ART.N_1]
      MainStyle = "Art"
      SubStyle = "Burnside 35"
      LensName = "Lensbaby"
      Positive = "Use Lensbaby Burnside 35 Optic lens, Features a central area of sharp focus and a swirling, adjustable vignette for creativity"
   [ART.N_2]
      MainStyle = "Art"
      SubStyle = "Circular Fisheye"
      LensName = "Lensbaby"
      Positive = "Use Lensbaby Circular Fisheye lens, Delivers a circular fisheye perspective for a unique and distorted artistic look"
   [ART.N_3]
      MainStyle = "Art"
      SubStyle = "Double Glass"
      LensName = "Lensbaby"
      Positive = "Use Lensbaby Double Glass Optic lens, Creates a unique, vintage look with a central area of sharp focus and a dreamy edge"
   [ART.N_4]
      MainStyle = "Art"
      SubStyle = "Double Glass Mouse"
      LensName = "Lensbaby"
      Positive = "Use Lensbaby Muse Double Glass Optic lens, Offers manual focus and creative effects for a personalized artistic touch"
   [ART.N_5]
      MainStyle = "Art"
      SubStyle = "Double Glass Spark"
      LensName = "Lensbaby"
      Positive = "Use Lensbaby Spark Double Glass Optic lens, Provides a burst of creativity with selective focus and vibrant image quality"
   [ART.N_6]
      MainStyle = "Art"
      SubStyle = "Edge 50"
      LensName = "Lensbaby"
      Positive = "Use Lensbaby Edge 50 Optic lens, Provides a slice of focus with a tilt effect for creative and artistic compositions"
   [ART.N_7]
      MainStyle = "Art"
      SubStyle = "Edge 80"
      LensName = "Lensbaby"
      Positive = "Use Lensbaby Composer Pro II Edge 80 Optic lens, Offers a slice of focus with a longer focal length for unique compositions"
   [ART.N_8]
      MainStyle = "Art"
      SubStyle = "Sol 45"
      LensName = "Lensbaby"
      Positive = "Use Lensbaby Sol 45mm f/3.5 lens, Features a selective focus design, allowing for creative and artistic compositions"
   [ART.N_9]
      MainStyle = "Art"
      SubStyle = "Sweet 35"
      LensName = "Lensbaby"
      Positive = "Use Lensbaby Composer Pro II Sweet 35 Optic lens, Allows for selective focus with a wider sweet spot for creative compositions"
   [ART.N_10]
      MainStyle = "Art"
      SubStyle = "Sweet 50"
      LensName = "Lensbaby"
      Positive = "Use Lensbaby Composer Pro II Sweet 50 Optic lens, Offers a unique, selective focus effect with a sweet spot for artistic portraits"
   [ART.N_11]
      MainStyle = "Art"
      SubStyle = "Sweet 80"
      LensName = "Lensbaby"
      Positive = "Use Lensbaby Sweet 80 Optic lens, Offers a sweet spot of focus with creative flare for artistic compositions"
   [ART.N_12]
      MainStyle = "Art"
      SubStyle = "Trio 28"
      LensName = "Lensbaby"
      Positive = "Use Lensbaby Trio 28 Sweet Twist Velvet Optics lens, A creative lens with three optics in one for diverse artistic effects"
   [ART.N_13]
      MainStyle = "Art"
      SubStyle = "Twist 40"
      LensName = "Lensbaby"
      Positive = "Use Lensbaby Twist 40 Optic lens, Features a unique swirling bokeh effect and sharp central focus for artistic shots"
   [ART.N_14]
      MainStyle = "Art"
      SubStyle = "Twist 50"
      LensName = "Lensbaby"
      Positive = "Use Lensbaby Twist 50 Optic lens, Creates a distinct twist effect in the bokeh for a unique and artistic look"
   [ART.N_15]
      MainStyle = "Art"
      SubStyle = "Twist 60"
      LensName = "Lensbaby"
      Positive = "Use ensbaby Twist 60 Optic lens, Creates a swirling bokeh effect around the subject, adding a touch of whimsy and fantasy"
   [ART.N_16]
      MainStyle = "Art"
      SubStyle = "Velvet 105"
      LensName = "Lensbaby"
      Positive = "Use Lensbaby Velvet 105mm f/2.5 lens, A longer focal length for soft and glowing portraits, emphasizing artistic expression"
   [ART.N_17]
      MainStyle = "Art"
      SubStyle = "Velvet 28"
      LensName = "Lensbaby"
      Positive = "Use Lensbaby Velvet 28mm f/2.5 lens, Wide-angle lens with a soft and glowing effect, perfect for artistic wide-angle shots"
   [ART.N_18]
      MainStyle = "Art"
      SubStyle = "Velvet 40"
      LensName = "Lensbaby"
      Positive = "Use Lensbaby Velvet 40mm f/2.8 lens, A mid-range focal length with a soft and ethereal effect for artistic shots"
   [ART.N_19]
      MainStyle = "Art"
      SubStyle = "Velvet 56"
      LensName = "Lensbaby"
      Positive = "Use Lensbaby Velvet 56mm f/1.6 lens, Creates a dreamy, ethereal effect with soft focus and beautiful, glowing bokeh"
   [ART.N_20]
      MainStyle = "Art"
      SubStyle = "Velvet 85"
      LensName = "Lensbaby"
      Positive = "Use Lensbaby Velvet 85mm f/1.8 lens, Similar to the Velvet 56mm, it offers a soft and glowing effect, ideal for portraits"
[LANDSCAPE]
   [LANDSCAPE.N_1]
      MainStyle = "Landscape"
      SubStyle = "Fish-eye Lens"
      LensName = "Rokinon"
      Positive = "Use Rokinon 12mm f/2.8 ED AS IF NCS UMC Fisheye lens, Provides a unique perspective with a 180-degree field of view"
   [LANDSCAPE.N_2]
      MainStyle = "Landscape"
      SubStyle = "Lightroom Lens"
      LensName = "Panasonic"
      Positive = "Use Panasonic Lumix S Pro 70-200mm f/4 O.I.S. lens, Corrects lens distortions in post-processing, ensuring optimal landscape images"
   [LANDSCAPE.N_3]
      MainStyle = "Landscape"
      SubStyle = "Macro Lens"
      LensName = "Nikon"
      Positive = "Use Nikon AF-S NIKKOR 105mm f/2.8G VR Micro lens, Can capture intricate details of small elements within a landscape"
   [LANDSCAPE.N_4]
      MainStyle = "Landscape"
      SubStyle = "Prime Lens"
      LensName = "Sigma"
      Positive = "Use Sigma 24mm f/1.4 DG HSM Art lens, Offers a wide aperture for low-light shooting and captures sharp landscapes"
   [LANDSCAPE.N_5]
      MainStyle = "Landscape"
      SubStyle = "Standard Zoom Lens"
      LensName = "Tamron"
      Positive = "Use Tamron 24-70mm f/2.8 Di VC USD G2 lens, Versatile lens for capturing a variety of landscapes with optimal clarity"
   [LANDSCAPE.N_6]
      MainStyle = "Landscape"
      SubStyle = "Telephoto Zoom Lens"
      LensName = "Sony"
      Positive = "Use Sony FE 70-200mm f/4 G OSS lens, Ideal for compressing distant landscapes and isolating specific details"
   [LANDSCAPE.N_7]
      MainStyle = "Landscape"
      SubStyle = "Tilt-Shift Lens"
      LensName = "Canon"
      Positive = "Use Canon TS-E 17mm f/4L lens, Allows for perspective control, ideal for architectural and scenic photography"
   [LANDSCAPE.N_8]
      MainStyle = "Landscape"
      SubStyle = "Ultra-Wide Lens"
      LensName = "Nikon"
      Positive = "Use Nikon AF-S NIKKOR 14-24mm f/2.8G lens, Offers an ultra-wide perspective, perfect for vast landscapes and architecture"
   [LANDSCAPE.N_9]
      MainStyle = "Landscape"
      SubStyle = "Weather-Sealed Lens"
      LensName = "Fujifilm"
      Positive = "Use Fujifilm XF 16-55mm f/2.8 R LM WR lens, Designed to withstand challenging weather conditions for outdoor shooting"
   [LANDSCAPE.N_10]
      MainStyle = "Landscape"
      SubStyle = "Wide-Angle Lens"
      LensName = "Canon"
      Positive = "Use Canon EF 16-35mm f/2.8L III USM lens, Ideal for capturing expansive landscapes and dramatic scenes"
[PORTRAIT]
   [PORTRAIT.N_1]
      MainStyle = "Portrait"
      SubStyle = "Art Lens"
      LensName = "Sony"
      Positive = "Use Sony FE 135mm f/1.8 GM lens, A premium lens for artistic portraits, offering stunning background separation"
   [PORTRAIT.N_2]
      MainStyle = "Portrait"
      SubStyle = "Bokeh Lens"
      LensName = "Sony"
      Positive = "Use Sony FE 50mm f/1.2 GM lens, Creates beautiful, artistic bokeh for unique and expressive portrait shots"
   [PORTRAIT.N_3]
      MainStyle = "Portrait"
      SubStyle = "Lightroom Lens"
      LensName = "Fujifilm"
      Positive = "Use Fujifilm XF 56mm f/1.2 R lens, Known for its beautiful rendering, ideal for capturing portraits with a cinematic look"
   [PORTRAIT.N_4]
      MainStyle = "Portrait"
      SubStyle = "Low Light Lens"
      LensName = "Sigma"
      Positive = "Use Sigma 35mm f/1.4 DG HSM Art lens, Excellent for low-light portrait photography, providing sharpness and clarity"
   [PORTRAIT.N_5]
      MainStyle = "Portrait"
      SubStyle = "Macro Lens"
      LensName = "Canon"
      Positive = "Use Canon RF 85mm f/2 Macro IS STM lens, Allows for creative close-up portraits, capturing intricate details"
   [PORTRAIT.N_6]
      MainStyle = "Portrait"
      SubStyle = "Portrait Lens"
      LensName = "Nikon"
      Positive = "Use Nikon AF-S NIKKOR 50mm f/1.8G lens, Versatile lens for portrait photography, offering excellent image quality"
   [PORTRAIT.N_7]
      MainStyle = "Portrait"
      SubStyle = "Prime Lens"
      LensName = "Canon"
      Positive = "Use Canon EF 85mm f/1.4L IS USM lens, Ideal for capturing stunning portraits with a creamy background blur (bokeh)"
   [PORTRAIT.N_8]
      MainStyle = "Portrait"
      SubStyle = "Telephoto Lens"
      LensName = "Canon"
      Positive = "Use Canon RF 70-200mm f/2.8L IS USM lens, Ideal for capturing portraits with a flattering compression effect"
   [PORTRAIT.N_9]
      MainStyle = "Portrait"
      SubStyle = "Vintage Lens"
      LensName = "Nikon"
      Positive = "Use Nikon NIKKOR 58mm f/1.4G lens, Delivers a unique character and vintage feel, adding charm to portrait images"
   [PORTRAIT.N_10]
      MainStyle = "Portrait"
      SubStyle = "Zoom Lens"
      LensName = "Tamron"
      Positive = "Use Tamron 28-75mm f/2.8 Di III RXD lens, Versatile zoom lens for capturing portraits in various settings with flexibility"
[PRODUCT]
   [PRODUCT.N_1]
      MainStyle = "Product"
      SubStyle = "Fisheye Lens"
      LensName = "Rokinon"
      Positive = "Use Rokinon 12mm f/2.8 ED AS IF NCS UMC Fisheye lens, Provides a unique, distorted perspective, ideal for creative product photography"
   [PRODUCT.N_2]
      MainStyle = "Product"
      SubStyle = "Lightroom Lens"
      LensName = "Tamron"
      Positive = "Use Tamron 24-70mm f/2.8 Di VC USD G2 (A032) lens, Corrects lens distortions in post-processing, ensuring optimal product images"
   [PRODUCT.N_3]
      MainStyle = "Product"
      SubStyle = "Macro Lens"
      LensName = "Canon"
      Positive = "Use Canon EF 100mm f/2.8L IS USM Macro lens, Perfect for close-up shots, capturing the finest details of your products"
   [PRODUCT.N_4]
      MainStyle = "Product"
      SubStyle = "Portrait Lens"
      LensName = "Canon"
      Positive = "Use Canon EF 85mm f/1.4L IS USM lens, Perfect for capturing product portraits with a beautiful background blur (bokeh)"
   [PRODUCT.N_5]
      MainStyle = "Product"
      SubStyle = "Prime Lens"
      LensName = "Canon"
      Positive = "Use Canon EF 50mm f/1.4 USM lens, Ideal for capturing intricate details and small products with its macro capabilities"
   [PRODUCT.N_6]
      MainStyle = "Product"
      SubStyle = "Standard Lens"
      LensName = "Sony"
      Positive = "Use Sony FE 24-70mm f/2.8 GM lens, Versatile lens suitable for a wide range of product photography scenarios"
   [PRODUCT.N_7]
      MainStyle = "Product"
      SubStyle = "Telephoto Lens"
      LensName = "Nikon"
      Positive = "Use Nikon AF-S NIKKOR 70-200mm f/2.8E FL ED VR lens, Brings distant products closer with exceptional clarity and image stabilization"
   [PRODUCT.N_8]
      MainStyle = "Product"
      SubStyle = "Tilt-Shift Lens"
      LensName = "Canon"
      Positive = "Use Canon TS-E 24mm f/3.5L II lens, Corrects perspective distortion, ideal for architectural and product photography"
   [PRODUCT.N_9]
      MainStyle = "Product"
      SubStyle = "Wide-Angle Lens"
      LensName = "Sigma"
      Positive = "Use Sigma 14mm f/1.8 DG HSM Art lens, Captures expansive product scenes with a wide perspective and excellent sharpness"
   [PRODUCT.N_10]
      MainStyle = "Product"
      SubStyle = "Zoom Lens"
      LensName = "Nikon"
      Positive = "Use Nikon AF-S NIKKOR 24-70mm f/2.8E ED VR lens, Versatile zoom lens for capturing various product shots with optimal clarity"
[SPORT]
   [SPORT.N_1]
      MainStyle = "Sport"
      SubStyle = "Action Stabilized Lens"
      LensName = "Sony"
      Positive = "Use Sony FE 200-600mm f/5.6-6.3 G OSS lens, Features optical stabilization for steady shots while capturing dynamic sports action"
   [SPORT.N_2]
      MainStyle = "Sport"
      SubStyle = "Fast Action Lens"
      LensName = "Panasonic"
      Positive = "Use Panasonic Leica DG Vario-Elmarit 50-200mm f/2.8-4.0 ASPH lens, Designed for capturing fast-paced sports action with precision"
   [SPORT.N_3]
      MainStyle = "Sport"
      SubStyle = "Fast Prime Lens"
      LensName = "Sony"
      Positive = "Use Sony FE 85mm f/1.4 GM lens, Ideal for capturing fast-paced sports with a wide aperture for excellent subject isolation"
   [SPORT.N_4]
      MainStyle = "Sport"
      SubStyle = "Sports Zoom Lens"
      LensName = "Tamron"
      Positive = "Use Tamron SP 150-600mm f/5-6.3 Di VC USD G2 lens, Offers a long reach for capturing sports action on the field with image stabilization"
   [SPORT.N_5]
      MainStyle = "Sport"
      SubStyle = "Super-Telephoto Lens"
      LensName = "Nikon"
      Positive = "Use Nikon AF-S NIKKOR 600mm f/4E FL ED VR lens, Offers extreme reach to capture distant sports action with exceptional detail"
   [SPORT.N_6]
      MainStyle = "Sport"
      SubStyle = "Telephoto Prime Lens"
      LensName = "Canon"
      Positive = "Use Canon EF 300mm f/2.8L IS II USM lens, Excellent for isolating subjects and capturing the intensity of sports moments"
   [SPORT.N_7]
      MainStyle = "Sport"
      SubStyle = "Telephoto Zoom Lens"
      LensName = "Canon"
      Positive = "Use Canon EF 70-200mm f/2.8L IS III USM lens, Ideal for capturing action from a distance with fast autofocus and image stabilization"
   [SPORT.N_8]
      MainStyle = "Sport"
      SubStyle = "Ultra-Wide Lens"
      LensName = "Nikon"
      Positive = "Use Nikon AF-S NIKKOR 14-24mm f/2.8G ED lens, Captures dynamic sports scenes with a unique perspective and wide field of view"
   [SPORT.N_9]
      MainStyle = "Sport"
      SubStyle = "Weather-Sealed Lens"
      LensName = "Fujifilm"
      Positive = "Use Fujifilm XF 50-140mm f/2.8 R LM OIS WR lens, Resistant to challenging weather conditions, ensuring reliability in outdoor sports"
   [SPORT.N_10]
      MainStyle = "Sport"
      SubStyle = "Wide-Angle Zoom Lens"
      LensName = "Sigma"
      Positive = "Use Sigma 24-70mm f/2.8 DG OS HSM Art lens, Versatile lens for capturing sports action in a variety of settings with optimal clarity"
[STREET]
   [STREET.N_1]
      MainStyle = "Street"
      SubStyle = "Bokeh Lens"
      LensName = "Sony"
      Positive = "Use Sony FE 85mm f/1.4 GM lens, Creates beautiful bokeh, ideal for isolating subjects and enhancing urban portraits"
   [STREET.N_2]
      MainStyle = "Street"
      SubStyle = "Lightroom Lens"
      LensName = "Tamron"
      Positive = "Use Tamron 17-28mm f/2.8 Di III RXD lens, Corrects lens distortions in post-processing, ensuring optimal urban images"
   [STREET.N_3]
      MainStyle = "Street"
      SubStyle = "Low Light Lens"
      LensName = "Fujifilm"
      Positive = "Use Fujifilm XF 56mm f/1.2 R lens, Excellent for low-light urban photography, providing sharpness and clarity"
   [STREET.N_4]
      MainStyle = "Street"
      SubStyle = "Prime Lens"
      LensName = "Canon"
      Positive = "Use Canon EF 35mm f/1.4L II USM lens, Offers a versatile focal length for street photography and urban scenes"
   [STREET.N_5]
      MainStyle = "Street"
      SubStyle = "Standard Zoom Lens"
      LensName = "Sony"
      Positive = "Use Sony FE 24-70mm f/2.8 GM lens, Versatile lens for capturing a variety of urban scenes with optimal clarity"
   [STREET.N_6]
      MainStyle = "Street"
      SubStyle = "Telephoto Zoom Lens"
      LensName = "Nikon"
      Positive = "Use Nikon AF-P NIKKOR 70-300mm f/4.5-5.6E ED VR lens, Ideal for capturing distant urban details and street scenes"
   [STREET.N_7]
      MainStyle = "Street"
      SubStyle = "Tilt-Shift Lens"
      LensName = "Canon"
      Positive = "Use Canon TS-E 45mm f/2.8 lens, Allows for creative perspective control, great for architectural and urban shots"
   [STREET.N_8]
      MainStyle = "Street"
      SubStyle = "Ultra-Wide Lens"
      LensName = "Panasonic"
      Positive = "Use Panasonic Lumix S Pro 16-35mm f/4 lens, Captures expansive urban scenes with a wide perspective and excellent sharpness"
   [STREET.N_9]
      MainStyle = "Street"
      SubStyle = "Vintage Lens"
      LensName = "Olympus"
      Positive = "Use Olympus M.Zuiko 25mm f/1.8 lens, Adds a vintage charm to urban scenes, providing a unique character to the images"
   [STREET.N_10]
      MainStyle = "Street"
      SubStyle = "Wide-Angle Lens"
      LensName = "Sigma"
      Positive = "Use Sigma 20mm f/1.4 DG HSM Art lens, Ideal for capturing urban landscapes and architecture with a wide perspective"
[WILD_LIFE]
   [WILD_LIFE.N_1]
      MainStyle = "Wild Life"
      SubStyle = "Documentary Lens"
      LensName = "Sigma"
      Positive = "Use Sigma 35mm f/1.4 DG HSM Art lens, Versatile lens for capturing candid moments and telling visual stories"
   [WILD_LIFE.N_2]
      MainStyle = "Wild Life"
      SubStyle = "Lightroom Lens"
      LensName = "Panasonic"
      Positive = "Use Panasonic Lumix S Pro 70-200mm f/4 O.I.S. lens, Corrects lens distortions in post-processing, ensuring optimal image quality"
   [WILD_LIFE.N_3]
      MainStyle = "Wild Life"
      SubStyle = "Low Light Lens"
      LensName = "Sony"
      Positive = "Use Sony FE 24mm f/1.4 GM lens, Excellent for shooting in low-light conditions, capturing atmospheric night scenes"
   [WILD_LIFE.N_4]
      MainStyle = "Wild Life"
      SubStyle = "Macro Lens"
      LensName = "Sony"
      Positive = "Use Sony FE 90mm f/2.8 Macro G OSS lens, Allows for detailed shots of small subjects and intricate details in nature"
   [WILD_LIFE.N_5]
      MainStyle = "Wild Life"
      SubStyle = "Portrait Lens"
      LensName = "Canon"
      Positive = "Use Canon RF 50mm f/1.2L USM lens, Ideal for capturing compelling portraits with a beautiful background blur"
   [WILD_LIFE.N_6]
      MainStyle = "Wild Life"
      SubStyle = "Standard Zoom Lens"
      LensName = "Tamron"
      Positive = "Use Tamron 24-70mm f/2.8 Di VC USD G2 lens, Versatile lens for a wide range of subjects, from portraits to documentary shots"
   [WILD_LIFE.N_7]
      MainStyle = "Wild Life"
      SubStyle = "Telephoto Prime Lens"
      LensName = "Fujifilm"
      Positive = "Use Fujifilm XF 200mm f/2 R LM OIS WR lens, Offers exceptional telephoto capabilities for isolating distant subjects"
   [WILD_LIFE.N_8]
      MainStyle = "Wild Life"
      SubStyle = "Telephoto Zoom Lens"
      LensName = "Canon"
      Positive = "Use Canon EF 100-400mm f/4.5-5.6L IS II USM lens, Ideal for wildlife photography, capturing distant subjects with superb clarity"
   [WILD_LIFE.N_9]
      MainStyle = "Wild Life"
      SubStyle = "Underwater Lens"
      LensName = "Nikon"
      Positive = "Use Nikon AF-S NIKKOR 16-35mm f/4G ED VR lens, Designed for capturing the beauty of underwater environments"
   [WILD_LIFE.N_10]
      MainStyle = "Wild Life"
      SubStyle = "Wide-Angle Lens"
      LensName = "Nikon"
      Positive = "Use Nikon AF-S NIKKOR 24mm f/1.4G ED lens, Perfect for capturing expansive landscapes and environmental portraits"
